--Name: Michael Greis
--Summary: This table is used to store ISO country information. Primarily it is used to translate the ISO 2 standards within the research database to ISO 3 for the visualization.



DROP TABLE kill_floor.country_information;

CREATE TABLE kill_floor.country_information
(
	country_name CHARACTER VARYING(100) NULL,
	modified_info CHARACTER VARYING(100) NULL,
	linked_country CHARACTER VARYING(100) NULL,
	country_iso3 CHARACTER VARYING(3) NULL,
	country_iso2 CHARACTER VARYING(2) NULL,
	grc CHARACTER VARYING(3)  NOT NULL,
	iso_number INTEGER NULL,
	country_alternate_name CHARACTER VARYING(100) NULL,
	imperative CHARACTER VARYING(100) NULL
);

SELECT *
FROM kill_floor.country_information;



INSERT INTO kill_floor.country_information VALUES('AFGHANISTAN','','','AFG','AF','AFG',4,'Afganistan','');
INSERT INTO kill_floor.country_information VALUES('','Added 26th October 2010','Finland','ALA','AX','ALA',248,'Åland Islands','Postal');
INSERT INTO kill_floor.country_information VALUES('Albania','','','ALB','AL','ALB',8,'Albania','');
INSERT INTO kill_floor.country_information VALUES('ALGERIA','','','DZA','DZ','ALG',12,'Algeria','');
INSERT INTO kill_floor.country_information VALUES('','','United States of America','ASM','AS','AMS',16,'American Samoa','Geographical');
INSERT INTO kill_floor.country_information VALUES('ANDORRA','','','AND','AD','AND',20,'Andorra','');
INSERT INTO kill_floor.country_information VALUES('ANGOLA','','','AGO','AO','ANG',24,'Angola','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','AIA','AI','ANU',660,'Anguilla','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('ANTIGUA AND BARBUDA','','','ATG','AG','ANT',28,'Antigua & Barbuda','');
INSERT INTO kill_floor.country_information VALUES('Argentina','','','ARG','AR','ARG',32,'Argentina','');
INSERT INTO kill_floor.country_information VALUES('Armenia','','','ARM','AM','ARM',51,'Armenia','');
INSERT INTO kill_floor.country_information VALUES('ARUBA','','Netherlands','ABW','AW','ARU',533,'Aruba','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Australia','','','AUS','AU','AST',36,'Australia','');
INSERT INTO kill_floor.country_information VALUES('Austria','','','AUT','AT','AUS',40,'Austria','');
INSERT INTO kill_floor.country_information VALUES('AZERBAIJAN','','','AZE','AZ','AZE',31,'Azerbaijan','');
INSERT INTO kill_floor.country_information VALUES('BAHAMAS','','','BHS','BS','BAH',44,'Bahamas','');
INSERT INTO kill_floor.country_information VALUES('BAHRAIN','','','BHR','BH','BAR',48,'Bahrain','');
INSERT INTO kill_floor.country_information VALUES('BANGLADESH','','','BGD','BD','BAN',50,'Bangladesh','');
INSERT INTO kill_floor.country_information VALUES('Barbados','','','BRB','BB','BAB',52,'Barbados','');
INSERT INTO kill_floor.country_information VALUES('BELARUS','','','BLR','BY','BEO',112,'Belarus','');
INSERT INTO kill_floor.country_information VALUES('Belgium','','','BEL','BE','BEL',56,'Belgium','');
INSERT INTO kill_floor.country_information VALUES('BELIZE','','','BLZ','BZ','BEI',84,'Belize','');
INSERT INTO kill_floor.country_information VALUES('Benin','','','BEN','BJ','BEN',204,'Benin','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','BMU','BM','BER',60,'Bermuda','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('BHUTAN','','','BTN','BT','BHU',64,'Bhutan','');
INSERT INTO kill_floor.country_information VALUES('BOLIVIA','','','BOL','BO','BOL',68,'Bolivia','');
INSERT INTO kill_floor.country_information VALUES('','ISO codes added 28th Dec. 2010','Netherlands','BES','BQ','BON',535,'Bonaire','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Bosnia-Herzegovina','','','BIH','BA','BOS',70,'Bosnia-Herzegovina','');
INSERT INTO kill_floor.country_information VALUES('BOTSWANA','','','BWA','BW','BOT',72,'Botswana','');
INSERT INTO kill_floor.country_information VALUES('Brazil','','','BRA','BR','BRA',76,'Brazil','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom, United States of America','IOT','IO','BIO',86,'British Indian Ocean Territory','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('British Virgin Islands','','United Kingdom','VGB','VG','BVI',92,'British Virgin Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('BRUNEI','','','BRN','BN','BRU',96,'Brunei Darussalam','');
INSERT INTO kill_floor.country_information VALUES('Bulgaria','','','BGR','BG','BUL',100,'Bulgaria','');
INSERT INTO kill_floor.country_information VALUES('BURKINA FASO','','','BFA','BF','BUK',854,'Burkina Faso','');
INSERT INTO kill_floor.country_information VALUES('BURUNDI','','','BDI','BI','BUU',108,'Burundi','');
INSERT INTO kill_floor.country_information VALUES('Cambodia','','','KHM','KH','CAM',116,'Cambodia','');
INSERT INTO kill_floor.country_information VALUES('Cameroon','','','CMR','CM','CAE',120,'Cameroon','');
INSERT INTO kill_floor.country_information VALUES('Canada','','','CAN','CA','CAN',124,'Canada','');
INSERT INTO kill_floor.country_information VALUES('CAPE VERDE','','','CPV','CV','CAP',132,'Cape Verde Islands','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','CYM','KY','CAY',136,'Cayman Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('CENTRAL AFRICAN, REPUBLIC','','','CAF','CF','CEN',140,'Central African Republic','');
INSERT INTO kill_floor.country_information VALUES('Chad','','','TCD','TD','CHA',148,'Chad','');
INSERT INTO kill_floor.country_information VALUES('CHILE','','','CHL','CL','CHI',152,'Chile','');
INSERT INTO kill_floor.country_information VALUES('CHINA','','','CHN','CN','CHN',156,'China','');
INSERT INTO kill_floor.country_information VALUES('','','Australia','CXR','CX','CHR',162,'Christmas Island','Geographical');
INSERT INTO kill_floor.country_information VALUES('','','Australia','CCK','CC','COC',166,'Cocos (Keeling) Islands','Geographical');
INSERT INTO kill_floor.country_information VALUES('Colombia','','','COL','CO','CLO',170,'Colombia','');
INSERT INTO kill_floor.country_information VALUES('COMOROS','','','COM','KM','COM',174,'Comoros','');
INSERT INTO kill_floor.country_information VALUES('CONGO','','','COG','CG','CNG',178,'Congo (Brazzaville)','');
INSERT INTO kill_floor.country_information VALUES('CONGO, DEMOCRATIC REPUBLIC OF','','','ZAR','CD','ZAI',180,'Congo (Kinshasa)','');
INSERT INTO kill_floor.country_information VALUES('COOK ISLANDS','','New Zealand','COK','CK','COO',184,'Cook Islands','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('Costa Rica','','','CRI','CR','COS',188,'Costa Rica','');
INSERT INTO kill_floor.country_information VALUES('Croatia','','','HRV','HR','CRO',191,'Croatia','');
INSERT INTO kill_floor.country_information VALUES('CUBA','','','CUB','CU','CUB',192,'Cuba','');
INSERT INTO kill_floor.country_information VALUES('','ISO codes added 28th Dec. 2010','Netherlands','CUW','CW','CUR',531,'Curaçao','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Cyprus','','','CYP','CY','CYP',196,'Cyprus','');
INSERT INTO kill_floor.country_information VALUES('Czech Republic','','','CZE','CZ','CZE',203,'Czech Republic','');
INSERT INTO kill_floor.country_information VALUES('Denmark','','','DNK','DK','DEN',208,'Denmark','');
INSERT INTO kill_floor.country_information VALUES('DJIBOUTI','','','DJI','DJ','DJI',262,'Djibouti','');
INSERT INTO kill_floor.country_information VALUES('DOMINIQUE','','','DMA','DM','DOI',212,'Dominica','');
INSERT INTO kill_floor.country_information VALUES('Dominican Republic','','','DOM','DO','DOM',214,'Dominican Republic','');
INSERT INTO kill_floor.country_information VALUES('EAST TIMOR','','','TLS','TL','ETI',626,'East Timor','');
INSERT INTO kill_floor.country_information VALUES('Ecuador','','','ECU','EC','ECU',218,'Ecuador','');
INSERT INTO kill_floor.country_information VALUES('EGYPT','','','EGY','EG','EGY',818,'Egypt','');
INSERT INTO kill_floor.country_information VALUES('El Salvador','','','SLV','SV','ELS',222,'El Salvador','');
INSERT INTO kill_floor.country_information VALUES('EQUATORIAL GUINEA','','','GNQ','GQ','EQA',226,'Equatorial Guinea','');
INSERT INTO kill_floor.country_information VALUES('ERITREA','','','ERI','ER','ERI',232,'Eritrea','');
INSERT INTO kill_floor.country_information VALUES('Estonia','','','EST','EE','EST',233,'Estonia','');
INSERT INTO kill_floor.country_information VALUES('ETHIOPIA','','','ETH','ET','ETH',231,'Ethiopia','');
INSERT INTO kill_floor.country_information VALUES('FAROE ISLANDS','','','FRO','FO','FAE',234,'Faeroe Islands','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','FLK','FK','FAL',238,'Falkland Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('FIJI','','','FJI','FJ','FIJ',242,'Fiji','');
INSERT INTO kill_floor.country_information VALUES('Finland','','','FIN','FI','FIN',246,'Finland','');
INSERT INTO kill_floor.country_information VALUES('France','','','FRA','FR','FRA',250,'France','');
INSERT INTO kill_floor.country_information VALUES('FRENCH GUYANA','','France','GUF','GF','FGU',254,'French Guiana','Geographical; Telephone');
INSERT INTO kill_floor.country_information VALUES('FRENCH POLYNESIA','Corrected 13th November 2010','France','PYF','PF','FPO',258,'French Polynesia','Geographical; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','','France','ATF','TF','FST',260,'French Southern Territories','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('GABON','','','GAB','GA','GAB',266,'Gabon','');
INSERT INTO kill_floor.country_information VALUES('GAMBIA','','','GMB','GM','GAM',270,'Gambia','');
INSERT INTO kill_floor.country_information VALUES('GEORGIA','','','GEO','GE','GEO',268,'Georgia','');
INSERT INTO kill_floor.country_information VALUES('Germany','','','DEU','DE','GER',276,'Germany','');
INSERT INTO kill_floor.country_information VALUES('Ghana','','','GHA','GH','GHA',288,'Ghana','');
INSERT INTO kill_floor.country_information VALUES('GIBRALTAR','','United Kingdom','GIB','GI','GIB',292,'Gibralter','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Greece','','','GRC','GR','GRE',300,'Greece','');
INSERT INTO kill_floor.country_information VALUES('GREENLAND','','Denmark','GRL','GL','GRN',304,'Greenland','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('GRENADA','','','GRD','GD','GRA',308,'Grenada','');
INSERT INTO kill_floor.country_information VALUES('GUADELOUPE','','France','GLP','GP','GUD',312,'Guadeloupe','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('','','United States of America','GUM','GU','GUM',316,'Guam','Geographical');
INSERT INTO kill_floor.country_information VALUES('Guatemala','','','GTM','GT','GUA',320,'Guatemala','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','GGY','GG','GUE',831,'Guernsey','Postal');
INSERT INTO kill_floor.country_information VALUES('Guinea','','','GIN','GN','GUI',324,'Guinea','');
INSERT INTO kill_floor.country_information VALUES('GUINEA BISSAU','','','GNB','GW','GUB',624,'Guinea-Bissau','');
INSERT INTO kill_floor.country_information VALUES('GUYANA','','','GUY','GY','GUY',328,'Guyana','');
INSERT INTO kill_floor.country_information VALUES('HAITI','','','HTI','HT','HAI',332,'Haiti','');
INSERT INTO kill_floor.country_information VALUES('HOLY SEE (VATICAN CITY STATE)','','','VAT','VA','VAT',336,'Holy See','');
INSERT INTO kill_floor.country_information VALUES('Honduras','','','HND','HN','HON',340,'Honduras','');
INSERT INTO kill_floor.country_information VALUES('Hong Kong','','China','HKG','HK','HOK',344,'Hong Kong','Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Hungary','','','HUN','HU','HUN',348,'Hungary','');
INSERT INTO kill_floor.country_information VALUES('Iceland','','','ISL','IS','ICE',352,'Iceland','');
INSERT INTO kill_floor.country_information VALUES('India','','','IND','IN','IND',356,'India','');
INSERT INTO kill_floor.country_information VALUES('INDONESIA','','','IDN','ID','INO',360,'Indonesia','');
INSERT INTO kill_floor.country_information VALUES('IRAN, ISLAMIC REPUBLIC OF','','','IRN','IR','IRA',364,'Iran','');
INSERT INTO kill_floor.country_information VALUES('IRAQ','','','IRQ','IQ','IRQ',368,'Iraq','');
INSERT INTO kill_floor.country_information VALUES('Ireland','','','IRL','IE','IRE',372,'Ireland','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','IMN','IM','ISL',833,'Isle of Man','Postal');
INSERT INTO kill_floor.country_information VALUES('Israel','','','ISR','IL','ISR',376,'Israel','');
INSERT INTO kill_floor.country_information VALUES('Italy','','','ITA','IT','ITA',380,'Italy','');
INSERT INTO kill_floor.country_information VALUES('COTE DIVOIRE','','','CIV','CI','IVO',384,'Ivory Coast','');
INSERT INTO kill_floor.country_information VALUES('Jamaica','','','JAM','JM','JAM',388,'Jamaica','');
INSERT INTO kill_floor.country_information VALUES('Japan','','','JPN','JP','JAP',392,'Japan','');
INSERT INTO kill_floor.country_information VALUES('JERSEY','','United Kingdom','JEY','JE','JER',832,'Jersey','Postal');
INSERT INTO kill_floor.country_information VALUES('JORDAN','','','JOR','JO','JOR',400,'Jordan','');
INSERT INTO kill_floor.country_information VALUES('KAZAKHSTAN','','','KAZ','KZ','KAZ',398,'Kazakhstan','');
INSERT INTO kill_floor.country_information VALUES('Kenya','','','KEN','KE','KEN',404,'Kenya','');
INSERT INTO kill_floor.country_information VALUES('KIRIBATI','','','KIR','KI','KII',296,'Kiribati','');
INSERT INTO kill_floor.country_information VALUES('','','Serbia','','','KOS',NULL,'Kosovo','Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('KUWAIT','','','KWT','KW','KUW',414,'Kuwait','');
INSERT INTO kill_floor.country_information VALUES('KYRGYZSTAN','','','KGZ','KG','KIR',417,'Kyrgyzstan','');
INSERT INTO kill_floor.country_information VALUES('LAOS, PEOPLES DEMOCRATIC REPUBLIC','','','LAO','LA','LAO',418,'Laos','');
INSERT INTO kill_floor.country_information VALUES('Latvia','','','LVA','LV','LAT',428,'Latvia','');
INSERT INTO kill_floor.country_information VALUES('LEBANON','','','LBN','LB','LEB',422,'Lebanon','');
INSERT INTO kill_floor.country_information VALUES('LESOTHO','','','LSO','LS','LES',426,'Lesotho','');
INSERT INTO kill_floor.country_information VALUES('LIBERIA','','','LBR','LR','LIR',430,'Liberia','');
INSERT INTO kill_floor.country_information VALUES('LIBYA','','','LBY','LY','LIB',434,'Libya','');
INSERT INTO kill_floor.country_information VALUES('LIECHTENSTEIN','','','LIE','LI','LIE',438,'Liechtenstein','');
INSERT INTO kill_floor.country_information VALUES('LITUANIA','','','LTU','LT','LIT',440,'Lithuania','');
INSERT INTO kill_floor.country_information VALUES('Luxembourg','','','LUX','LU','LUX',442,'Luxembourg','');
INSERT INTO kill_floor.country_information VALUES('MACAO','','China','MAC','MO','MCA',446,'Macau','Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('MACEDONIA, FORMER YUGOSLAV REPUBLIC OF','','','MKD','MK','MCE',807,'Macedonia','');
INSERT INTO kill_floor.country_information VALUES('MADAGASCAR','','','MDG','MG','MAD',450,'Madagascar','');
INSERT INTO kill_floor.country_information VALUES('MALAWI','','','MWI','MW','MAW',454,'Malawi','');
INSERT INTO kill_floor.country_information VALUES('Malaysia','','','MYS','MY','MAA',458,'Malaysia','');
INSERT INTO kill_floor.country_information VALUES('MALDIVES','','','MDV','MV','MAV',462,'Maldives','');
INSERT INTO kill_floor.country_information VALUES('MALI','','','MLI','ML','MAI',466,'Mali','');
INSERT INTO kill_floor.country_information VALUES('Malta','','','MLT','MT','MAL',470,'Malta','');
INSERT INTO kill_floor.country_information VALUES('MARSHALL ISLANDS','','','MHL','MH','MAR',584,'Marshall Islands','');
INSERT INTO kill_floor.country_information VALUES('MARTINIQUE','','France','MTQ','MQ','MAN',474,'Martinique','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('Mauritania','','','MRT','MR','MAU',478,'Mauritania','');
INSERT INTO kill_floor.country_information VALUES('MAURITIUS','','','MUS','MU','MAT',480,'Mauritius','');
INSERT INTO kill_floor.country_information VALUES('MAYOTTE','','France','MYT','YT','MAY',175,'Mayotte','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('Mexico','','','MEX','MX','MEX',484,'Mexico','');
INSERT INTO kill_floor.country_information VALUES('MICRONESIA, FEDERATED STATES OF','','','FSM','FM','MIC',583,'Micronesia','');
INSERT INTO kill_floor.country_information VALUES('MOLDOVA, REPUBLIC OF','','','MDA','MD','MOL',498,'Moldova','');
INSERT INTO kill_floor.country_information VALUES('Monaco','','','MCO','MC','MON',492,'Monaco','');
INSERT INTO kill_floor.country_information VALUES('MONGOLIA','','','MNG','MN','MOG',496,'Mongolia','');
INSERT INTO kill_floor.country_information VALUES('Montenegro','','','MNE','ME','MOE',499,'Montenegro','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','MSR','MS','MOT',500,'Montserrat','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Morocco','','','MAR','MA','MOR',504,'Morocco','');
INSERT INTO kill_floor.country_information VALUES('Mozambique','','','MOZ','MZ','MOZ',508,'Mozambique','');
INSERT INTO kill_floor.country_information VALUES('Myanmar','','','MMR','MM','BUR',104,'Myanmar','');
INSERT INTO kill_floor.country_information VALUES('','','Azerbaijan','','','NAG',NULL,'Nagorno-Karabakh','De Facto');
INSERT INTO kill_floor.country_information VALUES('NAMIBIA','','','NAM','NA','NAM',516,'Namibia','');
INSERT INTO kill_floor.country_information VALUES('NAURU','','','NRU','NR','NAU',520,'Nauru','');
INSERT INTO kill_floor.country_information VALUES('NEPAL','','','NPL','NP','NEP',524,'Nepal','');
INSERT INTO kill_floor.country_information VALUES('Netherlands Antilles','','','ANT','AN','NAN',530,'Netherlands Antilles','Legacy');
INSERT INTO kill_floor.country_information VALUES('Netherlands','','','NLD','NL','NET',528,'Netherlands','');
INSERT INTO kill_floor.country_information VALUES('NEW CALEDONIA','','France','NCL','NC','NCA',540,'New Caledonia','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('NEW ZEALAND','','','NZL','NZ','NEW',554,'New Zealand','');
INSERT INTO kill_floor.country_information VALUES('Nicaragua','','','NIC','NI','NIC',558,'Nicaragua','');
INSERT INTO kill_floor.country_information VALUES('Niger','','','NER','NE','NIE',562,'Niger','');
INSERT INTO kill_floor.country_information VALUES('Nigeria','','','NGA','NG','NIG',566,'Nigeria','');
INSERT INTO kill_floor.country_information VALUES('NIUE','','','NIU','NU','NIU',570,'Niue','');
INSERT INTO kill_floor.country_information VALUES('','','Australia','NFK','NF','NOF',574,'Norfolk Island','Geographical; Telephone');
INSERT INTO kill_floor.country_information VALUES('KOREA, PEOPLES DEMOCRATIC REPUBLIC OF','','','PRK','KP','NKO',408,'North Korea','');
INSERT INTO kill_floor.country_information VALUES('','','Cyprus','','','NCY',NULL,'Northern Cyprus','De Facto; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','','United States of America','MNP','MP','NMI',580,'Northern Mariana Islands','Geographical');
INSERT INTO kill_floor.country_information VALUES('Norway','','','NOR','NO','NOR',578,'Norway','');
INSERT INTO kill_floor.country_information VALUES('OMAN','','','OMN','OM','OMA',512,'Oman','');
INSERT INTO kill_floor.country_information VALUES('Pakistan','','','PAK','PK','PAK',586,'Pakistan','');
INSERT INTO kill_floor.country_information VALUES('PALAU','','','PLW','PW','PAL',585,'Palau','');
INSERT INTO kill_floor.country_information VALUES('PALESTINIAN OCCUPIED TERRITORY','','Israel','PSE','PS','PLA',275,'Palestinian Territories','');
INSERT INTO kill_floor.country_information VALUES('PANAMA','','','PAN','PA','PAN',591,'Panama','');
INSERT INTO kill_floor.country_information VALUES('PAPUA NEW GUINEA','','','PNG','PG','PAP',598,'Papua New Guinea','');
INSERT INTO kill_floor.country_information VALUES('PARAGUAY','','','PRY','PY','PAR',600,'Paraguay','');
INSERT INTO kill_floor.country_information VALUES('PERU','','','PER','PE','PER',604,'Peru','');
INSERT INTO kill_floor.country_information VALUES('Philippines','','','PHL','PH','PHI',608,'Philippines','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','PCN','PN','PIT',612,'Pitcairn Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Poland','','','POL','PL','POL',616,'Poland','');
INSERT INTO kill_floor.country_information VALUES('Portugal','','','PRT','PT','POR',620,'Portugal','');
INSERT INTO kill_floor.country_information VALUES('PUERTO RICO','','United States','PRI','PR','PUE',630,'Puerto Rico','Geographical');
INSERT INTO kill_floor.country_information VALUES('','','Somalia','','','PUN',NULL,'Puntland','De Facto');
INSERT INTO kill_floor.country_information VALUES('QATAR','','','QAT','QA','QAT',634,'Qatar','');
INSERT INTO kill_floor.country_information VALUES('Romania','','','ROU','RO','ROM',642,'Romania','');
INSERT INTO kill_floor.country_information VALUES('RUSSIA, FEDERATION OF','','','RUS','RU','RUS',643,'Russia','');
INSERT INTO kill_floor.country_information VALUES('RUANDA','','','RWA','RW','RWA',646,'Rwanda','');
INSERT INTO kill_floor.country_information VALUES('REUNION','','France','REU','RE','REU',638,'Réunion','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','ISO codes added 28th Dec. 2010','The Netherlands','BES','BQ','SAB',535,'Saba','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','','France','BLM','BL','STB',652,'Saint Barthélemy','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('SAINT KITTS AND NEVIS','','','KNA','KN','STC',659,'Saint Christopher & Nevis','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','SHN','SH','STH',654,'Saint Helena','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('SAINT LUCIA','','','LCA','LC','STL',662,'Saint Lucia','');
INSERT INTO kill_floor.country_information VALUES('','','France','MAF','MF','STM',663,'Saint Martin','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','','France','SPM','PM','SPM',666,'Saint Pierre & Miquelon','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('SAINT VINCENT AND THE GRENADINES','','','VCT','VC','STV',670,'Saint Vincent & The Grenadines','');
INSERT INTO kill_floor.country_information VALUES('SAMOA','','','WSM','WS','WSM',882,'Samoa','');
INSERT INTO kill_floor.country_information VALUES('SAINT MARINO','','','SMR','SM','SAN',674,'San Marino','');
INSERT INTO kill_floor.country_information VALUES('SAO TOME AND PRINCIPE','','','STP','ST','SAO',678,'Sao Tome & Principe','');
INSERT INTO kill_floor.country_information VALUES('SUADI ARABIA','','','SAU','SA','SAU',682,'Saudi Arabia','');
INSERT INTO kill_floor.country_information VALUES('Senegal','','','SEN','SN','SEN',686,'Senegal','');
INSERT INTO kill_floor.country_information VALUES('Serbia','','','SRB','RS','YUG',688,'Serbia','');
INSERT INTO kill_floor.country_information VALUES('SEYCHELLES','','','SYC','SC','SEY',690,'Seychelles','');
INSERT INTO kill_floor.country_information VALUES('SIERRA LEONE','','','SLE','SL','SIE',694,'Sierra Leone','');
INSERT INTO kill_floor.country_information VALUES('SINGAPORE','','','SGP','SG','SIN',702,'Singapore','');
INSERT INTO kill_floor.country_information VALUES('','ISO codes added 28th Dec. 2010','The Netherlands','BES','BQ','STE',535,'Sint Eustatius','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('','ISO codes added 28th Dec. 2010','The Netherlands','SXM','SX','SMA',534,'Sint Maarten','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Slovakia','','','SVK','SK','SLO',703,'Slovakia','');
INSERT INTO kill_floor.country_information VALUES('Slovenia','','','SVN','SI','SLV',705,'Slovenia','');
INSERT INTO kill_floor.country_information VALUES('SOLOMON ISLANDS','','','SLB','SB','SOL',90,'Solomon Islands','');
INSERT INTO kill_floor.country_information VALUES('SOMALIA','','','SOM','SO','SOM',706,'Somalia','');
INSERT INTO kill_floor.country_information VALUES('','','Somalia','SOM','SO','SOA',706,'Somaliland','De Facto');
INSERT INTO kill_floor.country_information VALUES('South Africa','','','ZAF','ZA','SAF',710,'South Africa','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','SGS','GS','SGE',239,'South Georgia & The South Sandwish Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('KOREA, REPUBLIC OF','','','KOR','KR','SKO',418,'South Korea','');
INSERT INTO kill_floor.country_information VALUES('','','Georgia','','','SOS',NULL,'South Ossetia','De Facto; Currency');
INSERT INTO kill_floor.country_information VALUES('SOUTH SUDAN','Added 22nd February 2011. ISO codes added 18th August 2011.','','SSD','SS','SSU',NULL,'South Sudan','');
INSERT INTO kill_floor.country_information VALUES('Spain','','','ESP','ES','SPA',724,'Spain','');
INSERT INTO kill_floor.country_information VALUES('SRI LANKA','','','LKA','LK','SRI',144,'Sri Lanka','');
INSERT INTO kill_floor.country_information VALUES('Sudan','','','SDN','SD','SUD',736,'Sudan','');
INSERT INTO kill_floor.country_information VALUES('SURINAM','','','SUR','SR','SUR',740,'Suriname','');
INSERT INTO kill_floor.country_information VALUES('SWAZILAND','','','SWZ','SZ','SWA',748,'Swaziland','');
INSERT INTO kill_floor.country_information VALUES('Sweden','','','SWE','SE','SWE',752,'Sweden','');
INSERT INTO kill_floor.country_information VALUES('Switzerland','','','CHE','CH','SWI',756,'Switzerland','');
INSERT INTO kill_floor.country_information VALUES('SYRIA, ARAB REPUBLIC','','','SYR','SY','SYR',760,'Syria','');
INSERT INTO kill_floor.country_information VALUES('TAIWAN','','China','TWN','TW','TAI',158,'Taiwan','');
INSERT INTO kill_floor.country_information VALUES('TAJIKISTAN','','','TJK','TJ','TAJ',762,'Tajikistan','');
INSERT INTO kill_floor.country_information VALUES('TANZANIA, UNITED RE UBLIC OF','','','TZA','TZ','TAN',834,'Tanzania','');
INSERT INTO kill_floor.country_information VALUES('THAILAND','','','THA','TH','THA',764,'Thailand','');
INSERT INTO kill_floor.country_information VALUES('TOGO','','','TGO','TG','TOG',768,'Togo','');
INSERT INTO kill_floor.country_information VALUES('','','New Zealand','TKL','TK','TOK',772,'Tokelau','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('TONGA','','','TON','TO','TON',776,'Tonga','');
INSERT INTO kill_floor.country_information VALUES('','','Moldova','','','TRA',NULL,'Transdniestria','De Facto');
INSERT INTO kill_floor.country_information VALUES('TRINIDAD AND TOBAGO','','','TTO','TT','TRI',780,'Trinidad & Tobago','');
INSERT INTO kill_floor.country_information VALUES('Tunisia','','','TUN','TN','TUN',788,'Tunisia','');
INSERT INTO kill_floor.country_information VALUES('Turkey','','','TUR','TR','TUR',792,'Turkey','');
INSERT INTO kill_floor.country_information VALUES('TURKMENISTAN','','','TKM','TM','TUK',795,'Turkmenistan','');
INSERT INTO kill_floor.country_information VALUES('','','United Kingdom','TCA','TC','TUC',796,'Turks & Caicos Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('TUVALU','','','TUV','TV','TUV',798,'Tuvalu','');
INSERT INTO kill_floor.country_information VALUES('Uganda','','','UGA','UG','UGA',800,'Uganda','');
INSERT INTO kill_floor.country_information VALUES('Ukraine','','','UKR','UA','UKR',804,'Ukraine','');
INSERT INTO kill_floor.country_information VALUES('United Arab Emirates','','','ARE','AE','UAE',784,'United Arab Emirates','');
INSERT INTO kill_floor.country_information VALUES('United Kingdom','','','GBR','GB','UNI',826,'United Kingdom','');
INSERT INTO kill_floor.country_information VALUES('United States','','','USA','US','USA',840,'United States','');
INSERT INTO kill_floor.country_information VALUES('US VIRGIN ISLANDS','','United States of America','VIR','VI','VIR',850,'United States Virgin Islands','Geographical');
INSERT INTO kill_floor.country_information VALUES('URUGUAY','','','URY','UY','URU',858,'Uruguay','');
INSERT INTO kill_floor.country_information VALUES('UZBEKISTAN','','','UZB','UZ','UZB',860,'Uzbekistan','');
INSERT INTO kill_floor.country_information VALUES('VANUATU','','','VUT','VU','VAN',548,'Vanuatu','');
INSERT INTO kill_floor.country_information VALUES('VENEZUELA','','','VEN','VE','VEN',862,'Venezuela','');
INSERT INTO kill_floor.country_information VALUES('VIETNAM','','','VNM','VN','VIE',704,'Vietnam','');
INSERT INTO kill_floor.country_information VALUES('','','France','WLF','WF','WAL',876,'Wallis & Futuna','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('WESTERN SAHARA','','Morocco','ESH','EH','WSA',732,'Western Sahara','Political');
INSERT INTO kill_floor.country_information VALUES('Yemen','','','YEM','YE','YEM',887,'Yemen','');
INSERT INTO kill_floor.country_information VALUES('ZAMBIA','','','ZMB','ZM','ZAM',894,'Zambia','');
INSERT INTO kill_floor.country_information VALUES('ZIMBABWE','','','ZWE','ZW','ZIM',716,'Zimbabwe','');



----------------------HAVE SOME DIRTY DATA IN THE ABOVE INSERT. RUN THIS IN SEQUENCE
DELETE FROM kill_floor.country_information
WHERE country_iso2 IN ('AI','MS','SH','SO','TC','TK','WF');

INSERT INTO kill_floor.country_information VALUES('Anguilla','','Anguilla','AIA','AI','ANU',660,'Anguilla','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Montserrat','','Montserrat','MSR','MS','MOT',500,'Montserrat','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Saint Helena','','Saint Helena','SHN','SH','STH',654,'Saint Helena','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Somalia','','','SOM','SO','SOM',706,'Somalia','');
INSERT INTO kill_floor.country_information VALUES('Turks & Caicos Islands','','United Kingdom','TCA','TC','TUC',796,'Turks & Caicos Islands','Geographical; Postal; Currency; Telephone');
INSERT INTO kill_floor.country_information VALUES('Tokelau','','New Zealand','TKL','TK','TOK',772,'Tokelau','Geographical; Postal; Telephone');
INSERT INTO kill_floor.country_information VALUES('Wallis & Futuna','','France','WLF','WF','WAL',876,'Wallis & Futuna','Geographical; Postal; Currency; Telephone');
